### ISSUE TITLE
[Feat] 3차 과제

### ISSUE THREAD

**Issue by 6uohul** [31st-IN-SOPT-iOS-Part/InyoungKim#5]
### 🍎 이슈 요약
3차 세미나 과제

### 🍏 ToDo
- [x] tab bar 구현
- [x] 친구 TableView 구현 
- [x] 채팅 CollectionView 구현
- [x] 사진 CollectionView 구현
- [x] 생각 과제
- [x] 심화 과제 - UISwipeConfiguration 를 이용해 cell 삭제
- [x] 심화 과제 - 사진 중복 선택 + 인덱싱
